### ISSUE TITLE
ipywidgets don't render

### ISSUE THREAD

**Issue by amihaiOff** [squaredtechnologies/vizly-notebook#17]
When trying to use ipywidgets the notebook doesn't render the widgets, rather it just displays the widget class in text

````
import ipywidgets as widgets
from IPython.display import display

button = widgets.Button(description='yo')
display(button)
````

Displays

````
Button(description='yo', style=ButtonStyle())
````

**Comment by samisahn** [comment]
Thanks for raising this. We're looking into supporting iPyWidgets shortly!

**Comment by samisahn** [comment]
IPyWidgets are now supported in v0.1.13 with [this commit](https://github.com/squaredtechnologies/thread/commit/12274b444d15863542f290ba0be188cf784a0fcc). 🎉

https://github.com/squaredtechnologies/thread/assets/26368245/285d8e7c-354c-4caf-a8a7-e8f3925a2992

Closing this out because it's working - please feel free to give it a try and raise any additional issues! This one was a bit of a doozy and there may be areas we need to revisit for truly full support.
